version: "3.9"
services:
  crimsonq:
    restart: "unless-stopped"
    image: yousefjwadi/crimsonq:latest
    build: .
    ports:
      - "9001:9001"
      - "8080:8080"
    volumes:
      - crimsonq:/CrimsonQ
    environment:
    - CRIMSONQ_RESP_PASS=cq!
    - CRIMSONQ_HTTP_USER=admin
    - CRIMSONQ_HTTP_PASS=password
volumes:
  crimsonq: {}