version: "3.9"
services:
  crimsonq:
    restart: "unless-stopped"
    image: yousefjwadi/crimsonq:latest
    build: .
    ports:
      - "9001:9001"
      - "8080:8080"
    volumes:
      - crimsonq:/CrimsonQ
volumes:
  crimsonq: {}